[package]
name = "vc-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cpal.workspace = true
hound = "3"
ringbuf.workspace = true
rustfft.workspace = true
vc-core = { path = "../vc-core" }
vc-signal = { path = "../vc-signal" }
