[package]
name = "vc-inference"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vc-core = { path = "../vc-core" }
ort.workspace = true
ndarray.workspace = true
